"""
ML Tag Suggestions API Endpoints

Provides endpoints for viewing and managing ML-generated tag suggestions.
"""

from typing import TYPE_CHECKING, Annotated, Literal

from fastapi import APIRouter, Depends, HTTPException, Query, Response, status
from sqlalchemy import desc, func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import settings
from app.core.auth import CurrentUser
from app.core.database import get_db
from app.core.logging import get_logger
from app.core.permissions import Permission, has_permission
from app.models.image import Images
from app.models.ml_tag_suggestion import MlTagSuggestions
from app.models.tag import Tags
from app.models.user import Users
from app.schemas.ml_tag_suggestion import (
    GenerateSuggestionsResponse,
    MlTagSuggestionResponse,
    MlTagSuggestionsListResponse,
    ReviewSuggestionsRequest,
    ReviewSuggestionsResponse,
)
from app.schemas.tag import TagResponse
from app.services.ml_suggestion_pipeline import generate_and_store_suggestions
from app.services.ml_suggestion_review import review_ml_tag_suggestions as apply_review
from app.tasks.queue import enqueue_job

if TYPE_CHECKING:
    from app.services.ml_service import MLTagSuggestionService

logger = get_logger(__name__)

router = APIRouter(prefix="/images", tags=["ml-tag-suggestions"])


async def _get_image_checking_access(
    db: AsyncSession,
    image_id: int,
    current_user: Users,
    detail: str,
) -> Images:
    """Fetch an image, requiring the caller to be its owner or hold IMAGE_TAG_ADD.

    Raises 404 if the image does not exist and 403 (with ``detail``) if the
    caller is neither the uploader nor a moderator with the tag-add permission.
    """
    image_result = await db.execute(
        select(Images).where(Images.image_id == image_id)  # type: ignore[arg-type]
    )
    image = image_result.scalar_one_or_none()
    if not image:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Image not found")

    is_owner = image.user_id == current_user.user_id
    is_admin = current_user.admin
    is_moderator = await has_permission(
        db,
        current_user.user_id,  # type: ignore[arg-type]
        Permission.IMAGE_TAG_ADD,
    )
    if not is_owner and not is_admin and not is_moderator:
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail=detail)

    return image


@router.get(
    "/{image_id}/ml-tag-suggestions",
    response_model=MlTagSuggestionsListResponse,
    response_description="List of ML tag suggestions with status counts",
)
async def get_ml_tag_suggestions(
    image_id: int,
    current_user: CurrentUser,
    status_filter: Annotated[
        Literal["pending", "approved", "rejected"] | None,
        Query(alias="status", description="Filter by suggestion status"),
    ] = None,
    db: AsyncSession = Depends(get_db),
) -> MlTagSuggestionsListResponse:
    """
    Get ML-generated tag suggestions for an image.

    This endpoint returns tag suggestions that were automatically generated by machine learning
    models when the image was uploaded. Suggestions can be filtered by their review status.

    **Permissions:**
    - Image uploader can view suggestions for their own images
    - Moderators with IMAGE_TAG_ADD permission can view suggestions for all images

    **Workflow:**
    1. ML models analyze the image during upload (background job)
    2. Tag suggestions are stored with confidence scores
    3. User/moderator reviews suggestions via this endpoint
    4. Approved suggestions create TagLinks (applied to image)

    **Examples:**

    Get all pending suggestions:
    ```text
    GET /api/v1/images/12345/ml-tag-suggestions?status=pending
    ```

    Get all suggestions (any status):
    ```text
    GET /api/v1/images/12345/ml-tag-suggestions
    ```

    **Response includes:**
    - List of suggestions with tag details and confidence scores
    - Count of suggestions by status (pending/approved/rejected) over ALL of the
      image's suggestions, regardless of the status filter
    - Model version that generated each suggestion

    Args:
        image_id: ID of the image
        current_user: Current authenticated user
        status_filter: Optional filter by status (pending/approved/rejected)
        db: Database session

    Returns:
        List of tag suggestions with counts by status

    Raises:
        HTTPException: 404 if image not found, 403 if permission denied
    """
    await _get_image_checking_access(
        db,
        image_id,
        current_user,
        detail="You can only view suggestions for your own images",
    )

    # Build query for suggestions
    query = select(MlTagSuggestions).where(
        MlTagSuggestions.image_id == image_id  # type: ignore[arg-type]
    )
    if status_filter:
        query = query.where(MlTagSuggestions.status == status_filter)  # type: ignore[arg-type]

    suggestions_result = await db.execute(
        query.order_by(desc(MlTagSuggestions.confidence))  # type: ignore[arg-type]
    )
    suggestions = list(suggestions_result.scalars().all())

    # Batch fetch all tags in one query to avoid N+1 problem
    tag_ids = [sugg.tag_id for sugg in suggestions]
    tag_result = await db.execute(
        select(Tags).where(Tags.tag_id.in_(tag_ids))  # type: ignore[union-attr]
    )
    tags_by_id = {tag.tag_id: tag for tag in tag_result.scalars().all()}

    # Build suggestion responses
    suggestion_responses = [
        MlTagSuggestionResponse(
            suggestion_id=sugg.suggestion_id,  # type: ignore[arg-type]
            tag=TagResponse.model_validate(tags_by_id[sugg.tag_id]),
            confidence=sugg.confidence,
            model_version=sugg.model_version,
            status=sugg.status,  # type: ignore[arg-type]
            created_at=sugg.created_at,  # type: ignore[arg-type]
            reviewed_at=sugg.reviewed_at,
        )
        for sugg in suggestions
    ]

    # Count by status (for all suggestions, not just filtered ones)
    status_counts_result = await db.execute(
        select(MlTagSuggestions.status, func.count(MlTagSuggestions.suggestion_id))  # type: ignore[call-overload, arg-type]
        .where(MlTagSuggestions.image_id == image_id)
        .group_by(MlTagSuggestions.status)
    )

    counts = {"pending": 0, "approved": 0, "rejected": 0}
    for status_val, count in status_counts_result:
        counts[status_val] = count

    return MlTagSuggestionsListResponse(
        image_id=image_id,
        suggestions=suggestion_responses,
        total=len(suggestion_responses),
        pending=counts["pending"],
        approved=counts["approved"],
        rejected=counts["rejected"],
    )


@router.post(
    "/{image_id}/ml-tag-suggestions/review",
    response_model=ReviewSuggestionsResponse,
    response_description="Review results with approval/rejection counts",
)
async def review_ml_tag_suggestions(
    image_id: int,
    request: ReviewSuggestionsRequest,
    current_user: CurrentUser,
    db: AsyncSession = Depends(get_db),
) -> ReviewSuggestionsResponse:
    """
    Approve or reject ML tag suggestions in batch.

    This endpoint allows users to review ML-generated tag suggestions. Approving a suggestion
    applies the tag to the image (creates a TagLink), while rejecting marks it as reviewed
    but does not apply the tag.

    **Permissions:**
    - Image uploader can review suggestions for their own images
    - Moderators with IMAGE_TAG_ADD permission can review suggestions for all images

    **Behavior:**
    - **Approve**: Creates TagLink (applies tag to image) and marks suggestion as approved
    - **Reject**: Marks suggestion as rejected (does not apply tag). Rejecting a
      previously-approved suggestion does NOT remove the TagLink it created.
    - Idempotent: Can re-review already reviewed suggestions
    - Prevents duplicate TagLinks (if tag already applied)
    - Tracks reviewer and review timestamp

    **Examples:**

    Approve some suggestions, reject others:
    ```json
    POST /api/v1/images/12345/ml-tag-suggestions/review
    {
      "suggestions": [
        {"suggestion_id": 1, "action": "approve"},
        {"suggestion_id": 2, "action": "approve"},
        {"suggestion_id": 3, "action": "reject"}
      ]
    }
    ```

    Response:
    ```json
    {
      "approved": 2,
      "rejected": 1,
      "errors": []
    }
    ```

    **Workflow:**
    1. User views suggestions via GET endpoint
    2. User selects suggestions to approve/reject
    3. Sends batch review request
    4. Approved tags are immediately applied to image
    5. User can add additional tags manually if needed

    Args:
        image_id: ID of the image
        request: Batch of suggestion reviews (approve/reject actions)
        current_user: Current authenticated user
        db: Database session

    Returns:
        Counts of approved/rejected suggestions and any errors

    Raises:
        HTTPException: 404 if image not found, 403 if permission denied
    """
    await _get_image_checking_access(
        db,
        image_id,
        current_user,
        detail="You can only review suggestions for your own images",
    )

    return await apply_review(image_id, request, current_user.user_id, db)  # type: ignore[arg-type]


@router.post(
    "/{image_id}/ml-tag-suggestions/generate",
    response_model=GenerateSuggestionsResponse,
    response_description="Tag suggestion generation triggered",
)
async def generate_ml_tag_suggestions(
    image_id: int,
    response: Response,
    current_user: CurrentUser,
    sync: Annotated[
        bool,
        Query(description="Run synchronously instead of queueing background job"),
    ] = False,
    db: AsyncSession = Depends(get_db),
) -> GenerateSuggestionsResponse:
    """
    Trigger ML tag suggestion generation for an existing image.

    **Modes:**
    - `sync=false` (default): Queues background job, returns immediately with job_id
    - `sync=true`: Runs ML inference inline (~0.6s), returns with suggestions_created count

    **Permissions:**
    - Image uploader can trigger generation for their own images
    - Users with IMAGE_TAG_ADD permission can trigger for any image

    **Behavior:**
    - Returns 503 when ML tag suggestions are disabled (ML_TAG_SUGGESTIONS_ENABLED)
    - New suggestions are created with 'pending' status
    - Existing suggestions are NOT deleted (idempotent)
    - Tags already applied to the image are skipped
    - Approved suggestions for removed tags are reset to 'pending'

    **Examples:**

    Async (background job):
    ```text
    POST /api/v1/images/12345/ml-tag-suggestions/generate
    ```

    Sync (inline, ~0.6s):
    ```text
    POST /api/v1/images/12345/ml-tag-suggestions/generate?sync=true
    ```

    Args:
        image_id: ID of the image
        response: FastAPI response (used to set the status code per mode)
        current_user: Current authenticated user
        sync: If true, run synchronously instead of queueing job
        db: Database session

    Returns:
        - Async: 202 with job_id
        - Sync: 200 with suggestions_created count

    Raises:
        HTTPException: 503 if disabled, 404 if image not found, 403 if permission denied
    """
    if not settings.ML_TAG_SUGGESTIONS_ENABLED:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="ML tag suggestions are disabled",
        )

    image = await _get_image_checking_access(
        db,
        image_id,
        current_user,
        detail="You can only generate suggestions for your own images",
    )

    if sync:
        # Run synchronously through the shared pipeline (loads the model on the
        # first sync call in this process).
        response.status_code = status.HTTP_200_OK
        try:
            suggestions_created = await generate_and_store_suggestions(
                db, image, await _get_ml_service()
            )
        except FileNotFoundError as exc:
            # The pipeline already logs the absolute path; do not leak it to the client.
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Image file not found",
            ) from exc
        return GenerateSuggestionsResponse(
            message="Tag suggestions generated",
            image_id=image_id,
            suggestions_created=suggestions_created,
        )
    else:
        # Queue background job
        response.status_code = status.HTTP_202_ACCEPTED
        job_id = await enqueue_job("generate_ml_tag_suggestions", image_id=image_id)
        return GenerateSuggestionsResponse(
            message="Tag suggestion generation queued",
            image_id=image_id,
            job_id=job_id,
        )


# Lazy-loaded ML service singleton for sync mode. The API process loads the
# ONNX model on the first synchronous generate call only.
_ml_service: MLTagSuggestionService | None = None


async def _get_ml_service() -> MLTagSuggestionService:
    """Get or create the ML service singleton.

    The import is function-local (mirroring app/tasks/worker.py) so that
    importing this router does not pull onnxruntime into the API import chain.
    The module global is only set once load_models() succeeds, so a failed load
    does not leave a half-initialized service cached.
    """
    global _ml_service
    if _ml_service is None:
        from app.services.ml_service import MLTagSuggestionService

        service = MLTagSuggestionService()
        await service.load_models()
        _ml_service = service
        logger.info("ml_service_loaded_for_sync_mode")
    return _ml_service
