-- Postgres baseline schema, generated by scripts/gen_pg_baseline.py
-- from the models as of the baseline revision, then FROZEN — do not
-- regenerate; ship changes as new migrations. 209 statements.
CREATE EXTENSION IF NOT EXISTS citext
-- ==stmt==
CREATE TYPE bannersize AS ENUM ('small', 'large')
-- ==stmt==
CREATE TYPE bannertheme AS ENUM ('dark', 'light')
-- ==stmt==
CREATE TYPE ml_suggestion_status AS ENUM ('pending', 'approved', 'rejected')
-- ==stmt==
CREATE TABLE images (
	filename VARCHAR(120),
	ext VARCHAR(10) NOT NULL,
	original_filename VARCHAR(255),
	md5_hash VARCHAR(32) NOT NULL,
	filesize INTEGER NOT NULL,
	width INTEGER NOT NULL,
	height INTEGER NOT NULL,
	caption VARCHAR(35) NOT NULL,
	miscmeta VARCHAR(255),
	source_url VARCHAR(2000),
	status INTEGER NOT NULL,
	rating FLOAT NOT NULL,
	image_id SERIAL NOT NULL,
	user_id INTEGER NOT NULL,
	locked INTEGER NOT NULL,
	posts INTEGER NOT NULL,
	favorites INTEGER NOT NULL,
	bayesian_rating FLOAT NOT NULL,
	num_ratings INTEGER NOT NULL,
	date_added TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	ip VARCHAR(45) NOT NULL,
	iqdb_hash VARCHAR(533),
	medium INTEGER NOT NULL,
	large INTEGER NOT NULL,
	status_user_id INTEGER,
	status_updated TIMESTAMP WITHOUT TIME ZONE,
	last_post TIMESTAMP WITHOUT TIME ZONE,
	total_pixels NUMERIC,
	replacement_id INTEGER,
	reason_category INTEGER,
	status_reason VARCHAR(1000),
	has_theme BOOLEAN NOT NULL,
	has_source BOOLEAN NOT NULL,
	has_artist BOOLEAN NOT NULL,
	has_character BOOLEAN NOT NULL,
	r2_location INTEGER NOT NULL,
	PRIMARY KEY (image_id)
)
-- ==stmt==
CREATE INDEX fk_images_status_user_id ON images (status_user_id)
-- ==stmt==
CREATE INDEX idx_favorites ON images (favorites)
-- ==stmt==
CREATE INDEX idx_posts ON images (posts)
-- ==stmt==
CREATE INDEX idx_total_pixels ON images (total_pixels)
-- ==stmt==
CREATE INDEX idx_images_has_artist ON images (has_artist, image_id)
-- ==stmt==
CREATE INDEX fk_images_user_id ON images (user_id)
-- ==stmt==
CREATE INDEX idx_filename ON images (filename)
-- ==stmt==
CREATE INDEX idx_status ON images (status)
-- ==stmt==
CREATE INDEX idx_images_has_theme ON images (has_theme, image_id)
-- ==stmt==
CREATE INDEX idx_images_has_character ON images (has_character, image_id)
-- ==stmt==
CREATE INDEX fk_images_replacement_id ON images (replacement_id)
-- ==stmt==
CREATE INDEX idx_bayesian_rating ON images (bayesian_rating)
-- ==stmt==
CREATE INDEX idx_last_post ON images (last_post)
-- ==stmt==
CREATE INDEX idx_top_images ON images (num_ratings)
-- ==stmt==
CREATE INDEX idx_images_has_source ON images (has_source, image_id)
-- ==stmt==
CREATE TABLE banners (
	name VARCHAR(255) NOT NULL,
	author VARCHAR(255),
	size bannersize NOT NULL,
	full_image VARCHAR(255),
	left_image VARCHAR(255),
	middle_image VARCHAR(255),
	right_image VARCHAR(255),
	supports_dark BOOLEAN NOT NULL,
	supports_light BOOLEAN NOT NULL,
	active BOOLEAN NOT NULL,
	in_r2 BOOLEAN NOT NULL,
	banner_id SERIAL NOT NULL,
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (banner_id),
	UNIQUE (full_image)
)
-- ==stmt==
CREATE TABLE eva_theme (
	theme_name VARCHAR(255) NOT NULL,
	banner VARCHAR(255) NOT NULL,
	theme_content VARCHAR,
	active_month_from INTEGER NOT NULL,
	active_month_to INTEGER NOT NULL,
	active_day_from INTEGER NOT NULL,
	active_day_to INTEGER NOT NULL,
	active INTEGER NOT NULL,
	theme_id SERIAL NOT NULL,
	PRIMARY KEY (theme_id)
)
-- ==stmt==
CREATE TABLE tips (
	tip VARCHAR(255),
	type INTEGER NOT NULL,
	id SERIAL NOT NULL,
	PRIMARY KEY (id)
)
-- ==stmt==
CREATE TABLE donations (
	date TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
	user_id INTEGER,
	nick VARCHAR(30),
	amount INTEGER,
	id SERIAL NOT NULL,
	PRIMARY KEY (id)
)
-- ==stmt==
CREATE INDEX donations_idx_date ON donations (date)
-- ==stmt==
CREATE TABLE image_ratings_avg (
	type VARCHAR(3) NOT NULL,
	avg FLOAT,
	PRIMARY KEY (type)
)
-- ==stmt==
CREATE TABLE ml_external_tags (
	id SERIAL NOT NULL,
	name VARCHAR(255) NOT NULL,
	category SMALLINT NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT unique_ml_external_tag_name UNIQUE (name)
)
-- ==stmt==
CREATE TABLE ml_models (
	id SMALLSERIAL NOT NULL,
	name VARCHAR(100) NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT unique_ml_model_name UNIQUE (name)
)
-- ==stmt==
CREATE TABLE groups (
	title VARCHAR(50),
	"desc" VARCHAR(75),
	group_id SERIAL NOT NULL,
	PRIMARY KEY (group_id)
)
-- ==stmt==
CREATE TABLE perms (
	title VARCHAR(50),
	"desc" VARCHAR(75),
	perm_id SERIAL NOT NULL,
	PRIMARY KEY (perm_id)
)
-- ==stmt==
CREATE TABLE user_perms (
	user_id INTEGER NOT NULL,
	perm_id INTEGER NOT NULL,
	permvalue INTEGER NOT NULL,
	PRIMARY KEY (user_id, perm_id)
)
-- ==stmt==
CREATE TABLE users (
	username CITEXT NOT NULL,
	location VARCHAR(100),
	website VARCHAR(100),
	interests VARCHAR(255),
	user_title VARCHAR(50),
	avatar VARCHAR(255) NOT NULL,
	avatar_in_r2 BOOLEAN NOT NULL,
	gender VARCHAR(50) NOT NULL,
	posts INTEGER NOT NULL,
	image_posts INTEGER NOT NULL,
	favorites INTEGER NOT NULL,
	user_id SERIAL NOT NULL,
	date_joined TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
	last_login TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	last_active TIMESTAMP WITHOUT TIME ZONE,
	active INTEGER NOT NULL,
	admin INTEGER NOT NULL,
	password VARCHAR(255) NOT NULL,
	password_type VARCHAR(10) NOT NULL,
	salt VARCHAR(16) NOT NULL,
	newpassword VARCHAR(40),
	newsalt VARCHAR(16),
	failed_login_attempts INTEGER NOT NULL,
	lockout_until TIMESTAMP WITHOUT TIME ZONE,
	email CITEXT NOT NULL,
	email_verified BOOLEAN NOT NULL,
	email_verification_token VARCHAR(64),
	email_verification_sent_at TIMESTAMP WITHOUT TIME ZONE,
	email_verification_expires_at TIMESTAMP WITHOUT TIME ZONE,
	password_reset_token VARCHAR(64),
	password_reset_sent_at TIMESTAMP WITHOUT TIME ZONE,
	password_reset_expires_at TIMESTAMP WITHOUT TIME ZONE,
	email_pm_pref INTEGER NOT NULL,
	spoiler_warning_pref INTEGER NOT NULL,
	thumb_layout INTEGER NOT NULL,
	thumb_size INTEGER NOT NULL,
	sorting_pref VARCHAR(100) NOT NULL,
	sorting_pref_order VARCHAR(10) NOT NULL,
	images_per_page INTEGER NOT NULL,
	show_all_images INTEGER NOT NULL,
	hide_reposts INTEGER NOT NULL,
	theme_preset VARCHAR(32),
	dark_mode BOOLEAN,
	maximgperday INTEGER NOT NULL,
	forum_id INTEGER,
	bookmark INTEGER,
	PRIMARY KEY (user_id)
)
-- ==stmt==
CREATE INDEX idx_user_favorites ON users (favorites)
-- ==stmt==
CREATE INDEX idx_password_reset_token ON users (password_reset_token)
-- ==stmt==
CREATE INDEX idx_email_verification_token ON users (email_verification_token)
-- ==stmt==
CREATE UNIQUE INDEX username ON users (username)
-- ==stmt==
CREATE INDEX idx_user_posts ON users (posts)
-- ==stmt==
CREATE INDEX fk_bookmark ON users (bookmark)
-- ==stmt==
CREATE INDEX idx_user_image_posts ON users (image_posts)
-- ==stmt==
CREATE TABLE user_tag_affinity (
	user_id INTEGER NOT NULL,
	tag_id INTEGER NOT NULL,
	pool_cnt INTEGER NOT NULL,
	fav_count INTEGER NOT NULL,
	upload_count INTEGER NOT NULL,
	rated_count INTEGER NOT NULL,
	rating_avg FLOAT,
	lift FLOAT,
	rating_delta FLOAT,
	affinity FLOAT NOT NULL,
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (user_id, tag_id)
)
-- ==stmt==
CREATE INDEX idx_user_tag_affinity_lookup ON user_tag_affinity (user_id, affinity)
-- ==stmt==
CREATE TABLE bans (
	action VARCHAR(50),
	reason VARCHAR,
	message VARCHAR(255),
	viewed INTEGER NOT NULL,
	ban_id SERIAL NOT NULL,
	user_id INTEGER NOT NULL,
	date TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	expires TIMESTAMP WITHOUT TIME ZONE,
	banned_by INTEGER,
	ip VARCHAR(15),
	PRIMARY KEY (ban_id),
	CONSTRAINT fk_bans_banned_by FOREIGN KEY(banned_by) REFERENCES users (user_id) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT fk_bans_user_id FOREIGN KEY(user_id) REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(user_id) REFERENCES users (user_id),
	FOREIGN KEY(banned_by) REFERENCES users (user_id)
)
-- ==stmt==
CREATE INDEX fk_bans_banned_by ON bans (banned_by)
-- ==stmt==
CREATE INDEX fk_bans_user_id ON bans (user_id)
-- ==stmt==
CREATE TABLE posts (
	post_text VARCHAR NOT NULL,
	image_id INTEGER,
	parent_comment_id INTEGER,
	deleted BOOLEAN NOT NULL,
	post_id SERIAL NOT NULL,
	user_id INTEGER NOT NULL,
	date TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
	update_count INTEGER NOT NULL,
	ip VARCHAR(45) NOT NULL,
	last_updated TIMESTAMP WITHOUT TIME ZONE,
	last_updated_user_id INTEGER,
	PRIMARY KEY (post_id),
	CONSTRAINT fk_posts_image_id FOREIGN KEY(image_id) REFERENCES images (image_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_posts_parent_comment_id FOREIGN KEY(parent_comment_id) REFERENCES posts (post_id) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT fk_posts_last_updated_user_id FOREIGN KEY(last_updated_user_id) REFERENCES users (user_id) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT fk_posts_user_id FOREIGN KEY(user_id) REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(user_id) REFERENCES users (user_id),
	FOREIGN KEY(last_updated_user_id) REFERENCES users (user_id)
)
-- ==stmt==
CREATE INDEX fk_posts_last_updated_user_id ON posts (last_updated_user_id)
-- ==stmt==
CREATE INDEX fk_posts_image_id ON posts (image_id)
-- ==stmt==
CREATE INDEX fk_posts_user_id ON posts (user_id)
-- ==stmt==
CREATE INDEX fk_posts_parent_comment_id ON posts (parent_comment_id)
-- ==stmt==
CREATE INDEX posts_idx_date ON posts (date)
-- ==stmt==
CREATE INDEX ix_posts_deleted ON posts (deleted)
-- ==stmt==
CREATE TABLE favorites (
	user_id INTEGER NOT NULL,
	image_id INTEGER NOT NULL,
	fav_date TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (user_id, image_id),
	CONSTRAINT fk_favorites_image_id FOREIGN KEY(image_id) REFERENCES images (image_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_favorites_user_id FOREIGN KEY(user_id) REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(user_id) REFERENCES users (user_id),
	FOREIGN KEY(image_id) REFERENCES images (image_id)
)
-- ==stmt==
CREATE INDEX fk_favorites_image_id ON favorites (image_id)
-- ==stmt==
CREATE TABLE image_ratings (
	user_id INTEGER NOT NULL,
	image_id INTEGER NOT NULL,
	rating INTEGER NOT NULL,
	date TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (user_id, image_id),
	CONSTRAINT fk_image_ratings_image_id FOREIGN KEY(image_id) REFERENCES images (image_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_image_ratings_user_id FOREIGN KEY(user_id) REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(user_id) REFERENCES users (user_id),
	FOREIGN KEY(image_id) REFERENCES images (image_id)
)
-- ==stmt==
CREATE INDEX fk_image_ratings_image_id ON image_ratings (image_id)
-- ==stmt==
CREATE TABLE image_reports (
	image_id INTEGER NOT NULL,
	user_id INTEGER NOT NULL,
	category INTEGER,
	reason_text VARCHAR,
	status INTEGER NOT NULL,
	admin_notes VARCHAR,
	report_id SERIAL NOT NULL,
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	reviewed_by INTEGER,
	reviewed_at TIMESTAMP WITHOUT TIME ZONE,
	PRIMARY KEY (report_id),
	FOREIGN KEY(image_id) REFERENCES images (image_id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(user_id) REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(reviewed_by) REFERENCES users (user_id) ON DELETE SET NULL ON UPDATE CASCADE
)
-- ==stmt==
CREATE INDEX fk_image_reports_image_id ON image_reports (image_id)
-- ==stmt==
CREATE INDEX fk_image_reports_reviewed_by ON image_reports (reviewed_by)
-- ==stmt==
CREATE INDEX fk_image_reports_user_id ON image_reports (user_id)
-- ==stmt==
CREATE INDEX idx_image_reports_status ON image_reports (status)
-- ==stmt==
CREATE TABLE user_banner_preferences (
	preferred_size bannersize NOT NULL,
	user_id INTEGER NOT NULL,
	PRIMARY KEY (user_id),
	CONSTRAINT fk_user_banner_prefs_user_id FOREIGN KEY(user_id) REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(user_id) REFERENCES users (user_id)
)
-- ==stmt==
CREATE TABLE user_banner_pins (
	size bannersize NOT NULL,
	theme bannertheme NOT NULL,
	id SERIAL NOT NULL,
	user_id INTEGER NOT NULL,
	banner_id INTEGER NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT fk_user_banner_pins_user_id FOREIGN KEY(user_id) REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_user_banner_pins_banner_id FOREIGN KEY(banner_id) REFERENCES banners (banner_id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(user_id) REFERENCES users (user_id),
	FOREIGN KEY(banner_id) REFERENCES banners (banner_id)
)
-- ==stmt==
CREATE UNIQUE INDEX uq_user_size_theme ON user_banner_pins (user_id, size, theme)
-- ==stmt==
CREATE TABLE quicklinks (
	link VARCHAR(32),
	quicklink_id SERIAL NOT NULL,
	user_id INTEGER,
	PRIMARY KEY (quicklink_id),
	CONSTRAINT fk_quicklinks_user_id FOREIGN KEY(user_id) REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(user_id) REFERENCES users (user_id)
)
-- ==stmt==
CREATE INDEX fk_quicklinks_user_id ON quicklinks (user_id)
-- ==stmt==
CREATE TABLE ml_raw_predictions (
	image_id INTEGER NOT NULL,
	model_id SMALLINT NOT NULL,
	external_tag_id INTEGER NOT NULL,
	confidence FLOAT NOT NULL,
	PRIMARY KEY (image_id, model_id, external_tag_id),
	FOREIGN KEY(image_id) REFERENCES images (image_id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(model_id) REFERENCES ml_models (id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(external_tag_id) REFERENCES ml_external_tags (id) ON DELETE CASCADE ON UPDATE CASCADE
)
-- ==stmt==
CREATE TABLE news (
	title VARCHAR(128),
	news_text VARCHAR,
	news_id SERIAL NOT NULL,
	user_id INTEGER NOT NULL,
	date TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	edited TIMESTAMP WITHOUT TIME ZONE,
	PRIMARY KEY (news_id),
	CONSTRAINT fk_news_user_id FOREIGN KEY(user_id) REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(user_id) REFERENCES users (user_id)
)
-- ==stmt==
CREATE INDEX fk_news_user_id ON news (user_id)
-- ==stmt==
CREATE TABLE group_perms (
	group_id INTEGER NOT NULL,
	perm_id INTEGER NOT NULL,
	permvalue INTEGER,
	PRIMARY KEY (group_id, perm_id),
	CONSTRAINT fk_group_perms_group_id FOREIGN KEY(group_id) REFERENCES groups (group_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_group_perms_perm_id FOREIGN KEY(perm_id) REFERENCES perms (perm_id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(group_id) REFERENCES groups (group_id),
	FOREIGN KEY(perm_id) REFERENCES perms (perm_id)
)
-- ==stmt==
CREATE INDEX fk_group_perms_perm_id ON group_perms (perm_id)
-- ==stmt==
CREATE TABLE user_groups (
	user_id INTEGER NOT NULL,
	group_id INTEGER NOT NULL,
	PRIMARY KEY (user_id, group_id),
	FOREIGN KEY(group_id) REFERENCES groups (group_id)
)
-- ==stmt==
CREATE TABLE privmsgs (
	subject VARCHAR(255) NOT NULL,
	text VARCHAR,
	from_user_id INTEGER NOT NULL,
	to_user_id INTEGER NOT NULL,
	thread_id VARCHAR(36) NOT NULL,
	privmsg_id SERIAL NOT NULL,
	viewed INTEGER NOT NULL,
	from_del INTEGER NOT NULL,
	to_del INTEGER NOT NULL,
	date TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (privmsg_id),
	CONSTRAINT fk_privmsgs_from_user_id FOREIGN KEY(from_user_id) REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_privmsgs_to_user_id FOREIGN KEY(to_user_id) REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(from_user_id) REFERENCES users (user_id),
	FOREIGN KEY(to_user_id) REFERENCES users (user_id)
)
-- ==stmt==
CREATE INDEX ix_privmsgs_thread_id ON privmsgs (thread_id)
-- ==stmt==
CREATE INDEX fk_privmsgs_to_user_id ON privmsgs (to_user_id)
-- ==stmt==
CREATE INDEX fk_privmsgs_from_user_id ON privmsgs (from_user_id)
-- ==stmt==
CREATE TABLE refresh_tokens (
	id SERIAL NOT NULL,
	user_id INTEGER NOT NULL,
	token_hash VARCHAR(255) NOT NULL,
	family_id VARCHAR(255) NOT NULL,
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
	expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	revoked BOOLEAN NOT NULL,
	revoked_at TIMESTAMP WITHOUT TIME ZONE,
	ip_address VARCHAR(45),
	user_agent VARCHAR(255),
	parent_token_id INTEGER,
	PRIMARY KEY (id),
	CONSTRAINT fk_refresh_tokens_user_id FOREIGN KEY(user_id) REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(user_id) REFERENCES users (user_id)
)
-- ==stmt==
CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens (user_id)
-- ==stmt==
CREATE UNIQUE INDEX ix_refresh_tokens_token_hash ON refresh_tokens (token_hash)
-- ==stmt==
CREATE UNIQUE INDEX idx_refresh_tokens_token_hash ON refresh_tokens (token_hash)
-- ==stmt==
CREATE INDEX idx_refresh_tokens_family_id ON refresh_tokens (family_id)
-- ==stmt==
CREATE INDEX ix_refresh_tokens_family_id ON refresh_tokens (family_id)
-- ==stmt==
CREATE TABLE tags (
	title CITEXT,
	"desc" VARCHAR(200),
	type INTEGER NOT NULL,
	tag_id SERIAL NOT NULL,
	date_added TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
	usage_count INTEGER NOT NULL,
	alias_of INTEGER,
	inheritedfrom_id INTEGER,
	user_id INTEGER,
	PRIMARY KEY (tag_id),
	CONSTRAINT fk_tags_alias_of FOREIGN KEY(alias_of) REFERENCES tags (tag_id) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT fk_tags_inheritedfrom_id FOREIGN KEY(inheritedfrom_id) REFERENCES tags (tag_id) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT fk_tags_user_id FOREIGN KEY(user_id) REFERENCES users (user_id) ON DELETE SET NULL ON UPDATE CASCADE,
	FOREIGN KEY(alias_of) REFERENCES tags (tag_id),
	FOREIGN KEY(inheritedfrom_id) REFERENCES tags (tag_id),
	FOREIGN KEY(user_id) REFERENCES users (user_id)
)
-- ==stmt==
CREATE INDEX fk_tags_user_id ON tags (user_id)
-- ==stmt==
CREATE INDEX fk_tags_alias ON tags (alias_of)
-- ==stmt==
CREATE INDEX type_alias ON tags (type, alias_of)
-- ==stmt==
CREATE INDEX idx_tags_title ON tags (title)
-- ==stmt==
CREATE INDEX fk_tags_inheritedfrom_id ON tags (inheritedfrom_id)
-- ==stmt==
CREATE INDEX idx_tags_usage_count ON tags (usage_count)
-- ==stmt==
CREATE TABLE user_suspensions (
	suspension_id SERIAL NOT NULL,
	user_id INTEGER NOT NULL,
	action VARCHAR(20) NOT NULL,
	actioned_by INTEGER,
	actioned_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
	suspended_until TIMESTAMP WITHOUT TIME ZONE,
	reason VARCHAR(500),
	acknowledged_at TIMESTAMP WITHOUT TIME ZONE,
	PRIMARY KEY (suspension_id),
	CONSTRAINT fk_user_suspensions_user_id FOREIGN KEY(user_id) REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_user_suspensions_actioned_by FOREIGN KEY(actioned_by) REFERENCES users (user_id) ON DELETE SET NULL ON UPDATE CASCADE,
	FOREIGN KEY(user_id) REFERENCES users (user_id),
	FOREIGN KEY(actioned_by) REFERENCES users (user_id)
)
-- ==stmt==
CREATE INDEX idx_user_suspensions_actioned_at ON user_suspensions (actioned_at)
-- ==stmt==
CREATE INDEX idx_user_suspensions_user_id ON user_suspensions (user_id)
-- ==stmt==
CREATE INDEX idx_user_suspensions_user_id_action_actioned_at ON user_suspensions (user_id, action, actioned_at)
-- ==stmt==
CREATE INDEX idx_user_suspensions_actioned_by ON user_suspensions (actioned_by)
-- ==stmt==
CREATE TABLE character_source_links (
	character_tag_id INTEGER NOT NULL,
	source_tag_id INTEGER NOT NULL,
	id SERIAL NOT NULL,
	created_by_user_id INTEGER,
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT fk_character_source_links_character_tag_id FOREIGN KEY(character_tag_id) REFERENCES tags (tag_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_character_source_links_source_tag_id FOREIGN KEY(source_tag_id) REFERENCES tags (tag_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_character_source_links_created_by_user_id FOREIGN KEY(created_by_user_id) REFERENCES users (user_id) ON DELETE SET NULL ON UPDATE CASCADE
)
-- ==stmt==
CREATE INDEX ix_character_source_links_created_by_user_id ON character_source_links (created_by_user_id)
-- ==stmt==
CREATE UNIQUE INDEX unique_character_source ON character_source_links (character_tag_id, source_tag_id)
-- ==stmt==
CREATE INDEX idx_source_tag_id ON character_source_links (source_tag_id)
-- ==stmt==
CREATE INDEX ix_character_source_links_source_tag_id ON character_source_links (source_tag_id)
-- ==stmt==
CREATE INDEX ix_character_source_links_character_tag_id ON character_source_links (character_tag_id)
-- ==stmt==
CREATE INDEX idx_character_tag_id ON character_source_links (character_tag_id)
-- ==stmt==
CREATE TABLE comment_reports (
	comment_id INTEGER NOT NULL,
	user_id INTEGER NOT NULL,
	category INTEGER,
	reason_text VARCHAR(1000),
	status INTEGER NOT NULL,
	admin_notes VARCHAR,
	report_id SERIAL NOT NULL,
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	reviewed_by INTEGER,
	reviewed_at TIMESTAMP WITHOUT TIME ZONE,
	PRIMARY KEY (report_id),
	FOREIGN KEY(comment_id) REFERENCES posts (post_id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(user_id) REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(reviewed_by) REFERENCES users (user_id) ON DELETE SET NULL ON UPDATE CASCADE
)
-- ==stmt==
CREATE INDEX idx_comment_reports_user_id ON comment_reports (user_id)
-- ==stmt==
CREATE INDEX idx_comment_reports_status_category ON comment_reports (status, category)
-- ==stmt==
CREATE INDEX idx_comment_reports_comment_id ON comment_reports (comment_id)
-- ==stmt==
CREATE INDEX idx_comment_reports_pending_per_user ON comment_reports (comment_id, user_id, status)
-- ==stmt==
CREATE INDEX idx_comment_reports_reviewed_by ON comment_reports (reviewed_by)
-- ==stmt==
CREATE TABLE image_report_tag_suggestions (
	report_id INTEGER NOT NULL,
	tag_id INTEGER NOT NULL,
	suggestion_type INTEGER NOT NULL,
	accepted BOOLEAN,
	suggestion_id SERIAL NOT NULL,
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (suggestion_id),
	CONSTRAINT unique_report_tag UNIQUE (report_id, tag_id),
	FOREIGN KEY(report_id) REFERENCES image_reports (report_id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(tag_id) REFERENCES tags (tag_id) ON DELETE CASCADE ON UPDATE CASCADE
)
-- ==stmt==
CREATE INDEX idx_accepted ON image_report_tag_suggestions (accepted)
-- ==stmt==
CREATE INDEX image_report_tag_suggestions_idx_tag_id ON image_report_tag_suggestions (tag_id)
-- ==stmt==
CREATE INDEX idx_report_id ON image_report_tag_suggestions (report_id)
-- ==stmt==
CREATE TABLE image_reviews (
	reason_category INTEGER NOT NULL,
	status INTEGER NOT NULL,
	outcome INTEGER NOT NULL,
	extension_used INTEGER NOT NULL,
	reason VARCHAR(1000),
	review_id SERIAL NOT NULL,
	image_id INTEGER NOT NULL,
	source_report_id INTEGER,
	initiated_by INTEGER,
	closed_by INTEGER,
	deadline TIMESTAMP WITHOUT TIME ZONE,
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	closed_at TIMESTAMP WITHOUT TIME ZONE,
	PRIMARY KEY (review_id),
	FOREIGN KEY(image_id) REFERENCES images (image_id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(source_report_id) REFERENCES image_reports (report_id) ON DELETE SET NULL ON UPDATE CASCADE,
	FOREIGN KEY(initiated_by) REFERENCES users (user_id) ON DELETE SET NULL ON UPDATE CASCADE,
	FOREIGN KEY(closed_by) REFERENCES users (user_id) ON DELETE SET NULL ON UPDATE CASCADE
)
-- ==stmt==
CREATE INDEX idx_image_reviews_deadline ON image_reviews (deadline)
-- ==stmt==
CREATE INDEX fk_image_reviews_initiated_by ON image_reviews (initiated_by)
-- ==stmt==
CREATE INDEX fk_image_reviews_closed_by ON image_reviews (closed_by)
-- ==stmt==
CREATE INDEX fk_image_reviews_source_report_id ON image_reviews (source_report_id)
-- ==stmt==
CREATE INDEX fk_image_reviews_image_id ON image_reviews (image_id)
-- ==stmt==
CREATE INDEX idx_image_reviews_status ON image_reviews (status)
-- ==stmt==
CREATE TABLE ml_tag_suggestions (
	image_id INTEGER NOT NULL,
	tag_id INTEGER NOT NULL,
	confidence FLOAT NOT NULL,
	model_version VARCHAR(100) NOT NULL,
	suggestion_id SERIAL NOT NULL,
	status ml_suggestion_status NOT NULL,
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	reviewed_at TIMESTAMP WITHOUT TIME ZONE,
	reviewed_by_user_id INTEGER,
	PRIMARY KEY (suggestion_id),
	CONSTRAINT unique_ml_suggestion_image_tag UNIQUE (image_id, tag_id),
	FOREIGN KEY(image_id) REFERENCES images (image_id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(tag_id) REFERENCES tags (tag_id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(reviewed_by_user_id) REFERENCES users (user_id) ON DELETE SET NULL ON UPDATE CASCADE
)
-- ==stmt==
CREATE INDEX idx_ml_suggestion_status_tag ON ml_tag_suggestions (status, tag_id, confidence)
-- ==stmt==
CREATE TABLE tag_audit_log (
	tag_id INTEGER NOT NULL,
	action_type VARCHAR(32) NOT NULL,
	old_title VARCHAR(128),
	new_title VARCHAR(128),
	old_type INTEGER,
	new_type INTEGER,
	old_desc VARCHAR(200),
	new_desc VARCHAR(200),
	old_alias_of INTEGER,
	new_alias_of INTEGER,
	old_parent_id INTEGER,
	new_parent_id INTEGER,
	character_tag_id INTEGER,
	source_tag_id INTEGER,
	link_url VARCHAR(2000),
	old_archive_url VARCHAR(2000),
	new_archive_url VARCHAR(2000),
	id SERIAL NOT NULL,
	user_id INTEGER,
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	CONSTRAINT fk_tag_audit_log_tag_id FOREIGN KEY(tag_id) REFERENCES tags (tag_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_tag_audit_log_user_id FOREIGN KEY(user_id) REFERENCES users (user_id) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT fk_tag_audit_log_old_alias_of FOREIGN KEY(old_alias_of) REFERENCES tags (tag_id) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT fk_tag_audit_log_new_alias_of FOREIGN KEY(new_alias_of) REFERENCES tags (tag_id) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT fk_tag_audit_log_old_parent_id FOREIGN KEY(old_parent_id) REFERENCES tags (tag_id) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT fk_tag_audit_log_new_parent_id FOREIGN KEY(new_parent_id) REFERENCES tags (tag_id) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT fk_tag_audit_log_character_tag_id FOREIGN KEY(character_tag_id) REFERENCES tags (tag_id) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT fk_tag_audit_log_source_tag_id FOREIGN KEY(source_tag_id) REFERENCES tags (tag_id) ON DELETE SET NULL ON UPDATE CASCADE
)
-- ==stmt==
CREATE INDEX idx_tag_audit_log_tag_id ON tag_audit_log (tag_id)
-- ==stmt==
CREATE INDEX idx_tag_audit_log_user_id ON tag_audit_log (user_id)
-- ==stmt==
CREATE INDEX idx_tag_audit_log_source_tag_id ON tag_audit_log (source_tag_id)
-- ==stmt==
CREATE INDEX idx_tag_audit_log_character_tag_id ON tag_audit_log (character_tag_id)
-- ==stmt==
CREATE INDEX idx_tag_audit_log_created_at ON tag_audit_log (created_at)
-- ==stmt==
CREATE INDEX idx_tag_audit_log_action_type ON tag_audit_log (action_type)
-- ==stmt==
CREATE TABLE tag_external_links (
	url VARCHAR(2000) NOT NULL,
	link_id SERIAL NOT NULL,
	tag_id INTEGER NOT NULL,
	date_added TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
	dead_at TIMESTAMP WITHOUT TIME ZONE,
	archive_url VARCHAR(2000),
	position INTEGER,
	PRIMARY KEY (link_id),
	CONSTRAINT fk_tag_external_links_tag_id FOREIGN KEY(tag_id) REFERENCES tags (tag_id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(tag_id) REFERENCES tags (tag_id)
)
-- ==stmt==
CREATE INDEX ix_tag_external_links_tag_id ON tag_external_links (tag_id)
-- ==stmt==
CREATE INDEX tag_external_links_idx_tag_id ON tag_external_links (tag_id)
-- ==stmt==
CREATE UNIQUE INDEX unique_tag_url ON tag_external_links (tag_id, url)
-- ==stmt==
CREATE TABLE tag_history (
	image_id INTEGER,
	tag_id INTEGER,
	action VARCHAR(1),
	date TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	tag_history_id SERIAL NOT NULL,
	user_id INTEGER,
	PRIMARY KEY (tag_history_id),
	CONSTRAINT fk_tag_history_image_id FOREIGN KEY(image_id) REFERENCES images (image_id) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT fk_tag_history_tag_id FOREIGN KEY(tag_id) REFERENCES tags (tag_id) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT fk_tag_history_user_id FOREIGN KEY(user_id) REFERENCES users (user_id) ON DELETE SET NULL ON UPDATE CASCADE,
	FOREIGN KEY(image_id) REFERENCES images (image_id),
	FOREIGN KEY(tag_id) REFERENCES tags (tag_id),
	FOREIGN KEY(user_id) REFERENCES users (user_id)
)
-- ==stmt==
CREATE INDEX idx_tag_history_tag_date ON tag_history (tag_id, date)
-- ==stmt==
CREATE INDEX idx_tag_history_user_date ON tag_history (user_id, date)
-- ==stmt==
CREATE INDEX fk_tag_history_tag_id ON tag_history (tag_id)
-- ==stmt==
CREATE INDEX user_id ON tag_history (user_id)
-- ==stmt==
CREATE INDEX image_id ON tag_history (image_id)
-- ==stmt==
CREATE TABLE tag_links (
	tag_id INTEGER NOT NULL,
	image_id INTEGER NOT NULL,
	date_linked TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	user_id INTEGER,
	PRIMARY KEY (tag_id, image_id),
	CONSTRAINT fk_tag_links_image_id FOREIGN KEY(image_id) REFERENCES images (image_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_tag_links_tag_id FOREIGN KEY(tag_id) REFERENCES tags (tag_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_tag_links_user_id FOREIGN KEY(user_id) REFERENCES users (user_id) ON DELETE SET NULL ON UPDATE CASCADE,
	FOREIGN KEY(tag_id) REFERENCES tags (tag_id),
	FOREIGN KEY(image_id) REFERENCES images (image_id),
	FOREIGN KEY(user_id) REFERENCES users (user_id)
)
-- ==stmt==
CREATE INDEX idx_tag_links_user_date_image ON tag_links (user_id, date_linked, image_id)
-- ==stmt==
CREATE INDEX fk_tag_links_user_id ON tag_links (user_id)
-- ==stmt==
CREATE INDEX fk_tag_links_image_id ON tag_links (image_id)
-- ==stmt==
CREATE INDEX idx_tag_links_tag_date ON tag_links (tag_id, date_linked)
-- ==stmt==
CREATE TABLE tag_mappings (
	external_tag VARCHAR(255) NOT NULL,
	confidence FLOAT NOT NULL,
	mapping_id SERIAL NOT NULL,
	internal_tag_id INTEGER,
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (mapping_id),
	CONSTRAINT unique_external_tag UNIQUE (external_tag),
	FOREIGN KEY(internal_tag_id) REFERENCES tags (tag_id) ON DELETE SET NULL ON UPDATE CASCADE
)
-- ==stmt==
CREATE TABLE user_favorite_tags (
	user_id INTEGER NOT NULL,
	tag_id INTEGER NOT NULL,
	position INTEGER NOT NULL,
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (user_id, tag_id),
	CONSTRAINT fk_user_favorite_tags_user_id FOREIGN KEY(user_id) REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_user_favorite_tags_tag_id FOREIGN KEY(tag_id) REFERENCES tags (tag_id) ON DELETE CASCADE ON UPDATE CASCADE
)
-- ==stmt==
CREATE INDEX idx_user_favorite_tags_tag_id ON user_favorite_tags (tag_id)
-- ==stmt==
CREATE TABLE admin_actions (
	action_id SERIAL NOT NULL,
	user_id INTEGER,
	action_type INTEGER NOT NULL,
	report_id INTEGER,
	review_id INTEGER,
	image_id INTEGER,
	details JSON,
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (action_id),
	CONSTRAINT fk_admin_actions_user_id FOREIGN KEY(user_id) REFERENCES users (user_id) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT fk_admin_actions_report_id FOREIGN KEY(report_id) REFERENCES image_reports (report_id) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT fk_admin_actions_review_id FOREIGN KEY(review_id) REFERENCES image_reviews (review_id) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT fk_admin_actions_image_id FOREIGN KEY(image_id) REFERENCES images (image_id) ON DELETE SET NULL ON UPDATE CASCADE
)
-- ==stmt==
CREATE INDEX idx_admin_actions_action_type ON admin_actions (action_type)
-- ==stmt==
CREATE INDEX idx_admin_actions_created_at ON admin_actions (created_at)
-- ==stmt==
CREATE INDEX fk_admin_actions_review_id ON admin_actions (review_id)
-- ==stmt==
CREATE INDEX fk_admin_actions_user_id ON admin_actions (user_id)
-- ==stmt==
CREATE INDEX fk_admin_actions_image_id ON admin_actions (image_id)
-- ==stmt==
CREATE INDEX fk_admin_actions_report_id ON admin_actions (report_id)
-- ==stmt==
CREATE TABLE character_source_link_pictures (
	image_id INTEGER NOT NULL,
	crop_x FLOAT NOT NULL,
	crop_y FLOAT NOT NULL,
	crop_w FLOAT NOT NULL,
	crop_h FLOAT NOT NULL,
	link_id INTEGER NOT NULL,
	set_by_user_id INTEGER,
	set_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (link_id),
	CONSTRAINT fk_cslink_pictures_link_id FOREIGN KEY(link_id) REFERENCES character_source_links (id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_cslink_pictures_image_id FOREIGN KEY(image_id) REFERENCES images (image_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_cslink_pictures_set_by_user_id FOREIGN KEY(set_by_user_id) REFERENCES users (user_id) ON DELETE SET NULL ON UPDATE CASCADE
)
-- ==stmt==
CREATE INDEX idx_cslink_pictures_image_id ON character_source_link_pictures (image_id)
-- ==stmt==
CREATE TABLE image_status_history (
	image_id INTEGER NOT NULL,
	old_status INTEGER NOT NULL,
	new_status INTEGER NOT NULL,
	id SERIAL NOT NULL,
	user_id INTEGER,
	reason_category INTEGER,
	reason VARCHAR(1000),
	report_id INTEGER,
	review_id INTEGER,
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	CONSTRAINT fk_image_status_history_image_id FOREIGN KEY(image_id) REFERENCES images (image_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_image_status_history_user_id FOREIGN KEY(user_id) REFERENCES users (user_id) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT fk_image_status_history_report_id FOREIGN KEY(report_id) REFERENCES image_reports (report_id) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT fk_image_status_history_review_id FOREIGN KEY(review_id) REFERENCES image_reviews (review_id) ON DELETE SET NULL ON UPDATE CASCADE
)
-- ==stmt==
CREATE INDEX idx_image_status_history_user_id ON image_status_history (user_id)
-- ==stmt==
CREATE INDEX idx_image_status_history_report_id ON image_status_history (report_id)
-- ==stmt==
CREATE INDEX idx_image_status_history_image_id ON image_status_history (image_id)
-- ==stmt==
CREATE INDEX idx_image_status_history_review_id ON image_status_history (review_id)
-- ==stmt==
CREATE INDEX idx_image_status_history_created_at ON image_status_history (created_at)
-- ==stmt==
CREATE TABLE review_votes (
	vote INTEGER,
	comment VARCHAR,
	vote_id SERIAL NOT NULL,
	image_id INTEGER,
	user_id INTEGER,
	review_id INTEGER,
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (vote_id),
	FOREIGN KEY(image_id) REFERENCES images (image_id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(user_id) REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(review_id) REFERENCES image_reviews (review_id) ON DELETE CASCADE ON UPDATE CASCADE
)
-- ==stmt==
CREATE INDEX fk_review_votes_user_id ON review_votes (user_id)
-- ==stmt==
CREATE INDEX fk_review_votes_review_id ON review_votes (review_id)
-- ==stmt==
CREATE INDEX idx_review_votes_image_user ON review_votes (image_id, user_id)
-- ==stmt==
CREATE TABLE user_favorite_links (
	user_id INTEGER NOT NULL,
	link_id INTEGER NOT NULL,
	position INTEGER NOT NULL,
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (user_id, link_id),
	CONSTRAINT fk_user_favorite_links_user_id FOREIGN KEY(user_id) REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_user_favorite_links_link_id FOREIGN KEY(link_id) REFERENCES character_source_links (id) ON DELETE CASCADE ON UPDATE CASCADE
)
-- ==stmt==
CREATE INDEX idx_user_favorite_links_link_id ON user_favorite_links (link_id)
-- ==stmt==
ALTER TABLE images ADD CONSTRAINT fk_images_replacement_id FOREIGN KEY(replacement_id) REFERENCES images (image_id) ON DELETE SET NULL ON UPDATE CASCADE
-- ==stmt==
ALTER TABLE users ADD FOREIGN KEY(bookmark) REFERENCES images (image_id)
-- ==stmt==
ALTER TABLE images ADD FOREIGN KEY(status_user_id) REFERENCES users (user_id)
-- ==stmt==
ALTER TABLE users ADD CONSTRAINT fk_bookmark FOREIGN KEY(bookmark) REFERENCES images (image_id) ON DELETE SET NULL ON UPDATE CASCADE
-- ==stmt==
ALTER TABLE images ADD FOREIGN KEY(replacement_id) REFERENCES images (image_id)
-- ==stmt==
ALTER TABLE images ADD CONSTRAINT fk_images_user_id FOREIGN KEY(user_id) REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE
-- ==stmt==
ALTER TABLE images ADD FOREIGN KEY(user_id) REFERENCES users (user_id)
-- ==stmt==
ALTER TABLE images ADD CONSTRAINT fk_images_status_user_id FOREIGN KEY(status_user_id) REFERENCES users (user_id) ON DELETE SET NULL ON UPDATE CASCADE
-- ==stmt==
ALTER TABLE users ADD CONSTRAINT ck_users_username_len CHECK (char_length(username) <= 30)
-- ==stmt==
ALTER TABLE users ADD CONSTRAINT ck_users_email_len CHECK (char_length(email) <= 120)
-- ==stmt==
ALTER TABLE tags ADD CONSTRAINT ck_tags_title_len CHECK (char_length(title) <= 255)
-- ==stmt==
CREATE OR REPLACE FUNCTION tag_links_counters_insert() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
        UPDATE tags SET usage_count = usage_count + 1 WHERE tag_id = NEW.tag_id;
        RETURN NULL;
        END $$
-- ==stmt==
DROP TRIGGER IF EXISTS tag_links_counters_insert ON tag_links
-- ==stmt==
CREATE TRIGGER tag_links_counters_insert AFTER INSERT ON tag_links
            FOR EACH ROW EXECUTE FUNCTION tag_links_counters_insert()
-- ==stmt==
CREATE OR REPLACE FUNCTION tag_links_counters_delete() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
        UPDATE tags SET usage_count = GREATEST(0, usage_count - 1) WHERE tag_id = OLD.tag_id;
        RETURN NULL;
        END $$
-- ==stmt==
DROP TRIGGER IF EXISTS tag_links_counters_delete ON tag_links
-- ==stmt==
CREATE TRIGGER tag_links_counters_delete AFTER DELETE ON tag_links
            FOR EACH ROW EXECUTE FUNCTION tag_links_counters_delete()
-- ==stmt==
CREATE OR REPLACE FUNCTION favorites_counters_insert() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN

        UPDATE images SET favorites = favorites + 1 WHERE image_id = NEW.image_id;
        UPDATE users SET favorites = favorites + 1 WHERE user_id = NEW.user_id;

        RETURN NULL;
        END $$
-- ==stmt==
DROP TRIGGER IF EXISTS favorites_counters_insert ON favorites
-- ==stmt==
CREATE TRIGGER favorites_counters_insert AFTER INSERT ON favorites
            FOR EACH ROW EXECUTE FUNCTION favorites_counters_insert()
-- ==stmt==
CREATE OR REPLACE FUNCTION favorites_counters_delete() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN

        UPDATE images SET favorites = favorites - 1 WHERE image_id = OLD.image_id;
        UPDATE users SET favorites = favorites - 1 WHERE user_id = OLD.user_id;

        RETURN NULL;
        END $$
-- ==stmt==
DROP TRIGGER IF EXISTS favorites_counters_delete ON favorites
-- ==stmt==
CREATE TRIGGER favorites_counters_delete AFTER DELETE ON favorites
            FOR EACH ROW EXECUTE FUNCTION favorites_counters_delete()
-- ==stmt==
CREATE OR REPLACE FUNCTION favorites_counters_update() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN

        IF OLD.image_id IS DISTINCT FROM NEW.image_id THEN
            UPDATE images SET favorites = favorites - 1 WHERE image_id = OLD.image_id;
            UPDATE images SET favorites = favorites + 1 WHERE image_id = NEW.image_id;
        END IF;
        IF OLD.user_id IS DISTINCT FROM NEW.user_id THEN
            UPDATE users SET favorites = favorites - 1 WHERE user_id = OLD.user_id;
            UPDATE users SET favorites = favorites + 1 WHERE user_id = NEW.user_id;
        END IF;

        RETURN NULL;
        END $$
-- ==stmt==
DROP TRIGGER IF EXISTS favorites_counters_update ON favorites
-- ==stmt==
CREATE TRIGGER favorites_counters_update AFTER UPDATE ON favorites
            FOR EACH ROW EXECUTE FUNCTION favorites_counters_update()
-- ==stmt==
CREATE OR REPLACE FUNCTION images_counters_insert() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
        UPDATE users SET image_posts = image_posts + 1 WHERE user_id = NEW.user_id;
        RETURN NULL;
        END $$
-- ==stmt==
DROP TRIGGER IF EXISTS images_counters_insert ON images
-- ==stmt==
CREATE TRIGGER images_counters_insert AFTER INSERT ON images
            FOR EACH ROW EXECUTE FUNCTION images_counters_insert()
-- ==stmt==
CREATE OR REPLACE FUNCTION images_counters_delete() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
        UPDATE users SET image_posts = image_posts - 1 WHERE user_id = OLD.user_id;
        RETURN NULL;
        END $$
-- ==stmt==
DROP TRIGGER IF EXISTS images_counters_delete ON images
-- ==stmt==
CREATE TRIGGER images_counters_delete AFTER DELETE ON images
            FOR EACH ROW EXECUTE FUNCTION images_counters_delete()
-- ==stmt==
CREATE OR REPLACE FUNCTION images_counters_update() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN

        IF OLD.user_id IS DISTINCT FROM NEW.user_id THEN
            UPDATE users SET image_posts = image_posts - 1 WHERE user_id = OLD.user_id;
            UPDATE users SET image_posts = image_posts + 1 WHERE user_id = NEW.user_id;
        END IF;

        RETURN NULL;
        END $$
-- ==stmt==
DROP TRIGGER IF EXISTS images_counters_update ON images
-- ==stmt==
CREATE TRIGGER images_counters_update AFTER UPDATE ON images
            FOR EACH ROW EXECUTE FUNCTION images_counters_update()
-- ==stmt==
CREATE OR REPLACE FUNCTION posts_counters_insert() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN

        IF NOT NEW.deleted THEN
            UPDATE images SET posts = posts + 1, last_post = NEW.date
                WHERE image_id = NEW.image_id;
            UPDATE users SET posts = posts + 1 WHERE user_id = NEW.user_id;
        END IF;

        RETURN NULL;
        END $$
-- ==stmt==
DROP TRIGGER IF EXISTS posts_counters_insert ON posts
-- ==stmt==
CREATE TRIGGER posts_counters_insert AFTER INSERT ON posts
            FOR EACH ROW EXECUTE FUNCTION posts_counters_insert()
-- ==stmt==
CREATE OR REPLACE FUNCTION posts_counters_update() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN

        IF OLD.deleted = false AND NEW.deleted = true THEN
            UPDATE images
            SET posts = posts - 1,
                last_post = (SELECT MAX(date) FROM posts
                             WHERE image_id = NEW.image_id AND NOT deleted)
            WHERE image_id = NEW.image_id;
            UPDATE users SET posts = posts - 1 WHERE user_id = NEW.user_id;
        ELSIF OLD.deleted = true AND NEW.deleted = false THEN
            UPDATE images
            SET posts = posts + 1,
                last_post = (SELECT MAX(date) FROM posts
                             WHERE image_id = NEW.image_id AND NOT deleted)
            WHERE image_id = NEW.image_id;
            UPDATE users SET posts = posts + 1 WHERE user_id = NEW.user_id;
        ELSE
            IF OLD.image_id IS DISTINCT FROM NEW.image_id THEN
                UPDATE images
                SET posts = posts - 1,
                    last_post = (SELECT MAX(date) FROM posts
                                 WHERE image_id = OLD.image_id AND NOT deleted)
                WHERE image_id = OLD.image_id;
                UPDATE images
                SET posts = posts + 1,
                    last_post = (SELECT MAX(date) FROM posts
                                 WHERE image_id = NEW.image_id AND NOT deleted)
                WHERE image_id = NEW.image_id;
            END IF;
            IF OLD.user_id IS DISTINCT FROM NEW.user_id THEN
                UPDATE users SET posts = posts - 1 WHERE user_id = OLD.user_id;
                UPDATE users SET posts = posts + 1 WHERE user_id = NEW.user_id;
            END IF;
        END IF;

        RETURN NULL;
        END $$
-- ==stmt==
DROP TRIGGER IF EXISTS posts_counters_update ON posts
-- ==stmt==
CREATE TRIGGER posts_counters_update AFTER UPDATE ON posts
            FOR EACH ROW EXECUTE FUNCTION posts_counters_update()
-- ==stmt==
CREATE OR REPLACE FUNCTION posts_counters_delete() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN

        IF NOT OLD.deleted THEN
            UPDATE images
            SET posts = posts - 1,
                last_post = (SELECT MAX(date) FROM posts
                             WHERE image_id = OLD.image_id AND NOT deleted)
            WHERE image_id = OLD.image_id;
            UPDATE users SET posts = posts - 1 WHERE user_id = OLD.user_id;
        END IF;

        RETURN NULL;
        END $$
-- ==stmt==
DROP TRIGGER IF EXISTS posts_counters_delete ON posts
-- ==stmt==
CREATE TRIGGER posts_counters_delete AFTER DELETE ON posts
            FOR EACH ROW EXECUTE FUNCTION posts_counters_delete()
