"""Generate the frozen DDL for the Postgres Alembic baseline.

Captures exactly what `app.core.pg_schema.build_pg_schema` would run — the
citext extension, create_all DDL (with cross-table index-name collisions
deduped), the length CHECK constraints, and the counter triggers — as a list
of single statements joined by `-- ==stmt==` marker lines (asyncpg cannot run
multi-command prepared statements, and parsing $$-quoted bodies is fragile;
the marker sidesteps both).

Used ONCE to produce alembic_pg/versions/0001_pg_baseline.sql. A merged
baseline is frozen (repo migration rule): do NOT rerun this against it —
subsequent model changes ship as incremental migrations in alembic_pg/.

    uv run python scripts/gen_pg_baseline.py
"""

from pathlib import Path

from sqlalchemy import create_mock_engine

OUT = Path(__file__).resolve().parent.parent / "alembic_pg" / "versions" / "0001_pg_baseline.sql"
MARKER = "-- ==stmt=="


def main() -> None:
    # app.main, not app.models: the models package __init__ does not import
    # every model module, but the app wiring does.
    from sqlmodel import SQLModel

    import app.main  # noqa: F401
    from app.core.pg_schema import _LENGTH_CHECKS, dedupe_index_names
    from app.core.pg_triggers import _TRIGGER_DDL

    dedupe_index_names(SQLModel.metadata)

    statements: list[str] = ["CREATE EXTENSION IF NOT EXISTS citext"]

    def capture(sql, *args, **kwargs) -> None:  # type: ignore[no-untyped-def]
        compiled = str(sql.compile(dialect=engine.dialect)).strip()
        # Per-line rstrip: compiled DDL carries trailing spaces that the
        # pre-commit whitespace hook would strip, drifting the frozen file
        # from generator output.
        statements.append("\n".join(line.rstrip() for line in compiled.splitlines()))

    engine = create_mock_engine("postgresql+asyncpg://", capture)
    SQLModel.metadata.create_all(engine, checkfirst=False)

    statements.extend(_LENGTH_CHECKS)
    statements.extend(stmt.strip() for stmt in _TRIGGER_DDL)

    header = (
        "-- Postgres baseline schema, generated by scripts/gen_pg_baseline.py\n"
        "-- from the models as of the baseline revision, then FROZEN — do not\n"
        f"-- regenerate; ship changes as new migrations. {len(statements)} statements.\n"
    )
    OUT.write_text(header + f"\n{MARKER}\n".join(statements) + "\n")
    print(f"wrote {OUT} — {len(statements)} statements")


if __name__ == "__main__":
    main()
