"""Regenerate docs/plans/README.md from the plan files on disk.

Plans live in quarter directories (docs/plans/YYYY-QN/) and are named
<date>-<slug>-design.md / <date>-<slug>-impl.md. This groups them by slug so a
design and its implementation plan share one row, and writes an index grouped
by quarter, newest first.

Run after adding or moving plans:

    uv run python scripts/gen_plans_index.py
"""

import re
from collections import defaultdict
from pathlib import Path
from typing import Any

PLANS_DIR = Path(__file__).resolve().parent.parent / "docs" / "plans"
INDEX = PLANS_DIR / "README.md"
QUARTER_DIR = re.compile(r"^\d{4}-Q[1-4]$")
FILENAME = re.compile(r"^(\d{4}-\d{2}-\d{2})-(.+?)(?:-(design|impl))?\.md$")

EXCEPTIONS_START = "<!-- exceptions:start -->"
EXCEPTIONS_END = "<!-- exceptions:end -->"

PREAMBLE = f"""# Plans

Design and implementation plans, grouped by the quarter they were written in.

**These are point-in-time records.** A plan describes what was intended on its
date; it is not revised afterwards and does not describe current code. When you
need to know how something works today, read the code. When you need to know why
a decision went the way it did, read `docs/adr/` — decisions worth keeping are
distilled there.

**Assume a plan was implemented unless it is listed under Exceptions below.**

Everything outside the Exceptions block is generated by
`scripts/gen_plans_index.py`; rerun it after adding or moving a plan. The
Exceptions block is maintained by hand and is preserved across regeneration.

## Exceptions

{EXCEPTIONS_START}
| Plan | State | Notes |
| --- | --- | --- |
| [forum API](2026-Q3/2026-07-06-forum-api-impl.md) | not implemented | No forum router, models, or schemas exist. Spec lives on the frontend repo's unmerged `feat/forum` branch. |
| [external artist identity](2026-Q3/2026-08-01-external-artist-identity-impl.md) | not implemented | No `artist_identity` service, backfill, or routes exist. |
{EXCEPTIONS_END}
"""


def title_of(path: Path, fallback: str) -> str:
    """First markdown H1 in the file, or a humanised slug."""
    try:
        for line in path.read_text(encoding="utf-8").splitlines():
            if line.startswith("# "):
                return line[2:].strip()
    except (UnicodeDecodeError, OSError):
        pass
    return fallback.replace("-", " ").capitalize()


def preserved_preamble() -> str:
    """PREAMBLE, but carrying over any hand-edited Exceptions block."""
    if not INDEX.exists():
        return PREAMBLE
    current = INDEX.read_text(encoding="utf-8")
    start = current.find(EXCEPTIONS_START)
    end = current.find(EXCEPTIONS_END)
    if start == -1 or end == -1 or end < start:
        return PREAMBLE
    kept = current[start + len(EXCEPTIONS_START) : end]
    head, _, tail = PREAMBLE.partition(EXCEPTIONS_START)
    _, _, after = tail.partition(EXCEPTIONS_END)
    return f"{head}{EXCEPTIONS_START}{kept}{EXCEPTIONS_END}{after}"


def main() -> None:
    # quarter -> slug -> {"date": str, "docs": {kind: filename}}
    quarters: dict[str, dict[str, dict[str, Any]]] = defaultdict(
        lambda: defaultdict(dict)
    )

    for quarter_dir in PLANS_DIR.iterdir():
        if not quarter_dir.is_dir() or not QUARTER_DIR.match(quarter_dir.name):
            continue
        for plan in quarter_dir.glob("*.md"):
            match = FILENAME.match(plan.name)
            if not match:
                continue
            date, slug, kind = match.groups()
            entry = quarters[quarter_dir.name][slug]
            entry.setdefault("date", date)
            entry["date"] = min(entry["date"], date)
            entry.setdefault("docs", {})[kind or "notes"] = plan.name

    lines = [preserved_preamble()]
    for quarter in sorted(quarters, reverse=True):
        efforts = quarters[quarter]
        lines.append(f"\n## {quarter}\n")
        lines.append("| Date | Effort | Docs |")
        lines.append("| --- | --- | --- |")
        for slug, entry in sorted(
            efforts.items(), key=lambda item: (item[1]["date"], item[0]), reverse=True
        ):
            docs = entry["docs"]
            # The design doc names the effort best; fall back to impl, then notes.
            preferred = next(k for k in ("design", "impl", "notes") if k in docs)
            name = title_of(PLANS_DIR / quarter / docs[preferred], slug)
            links = " · ".join(
                f"[{kind}]({quarter}/{filename})"
                for kind, filename in sorted(docs.items())
            )
            lines.append(f"| {entry['date']} | {name} | {links} |")

    doc_count = sum(len(e["docs"]) for q in quarters.values() for e in q.values())
    effort_count = sum(len(q) for q in quarters.values())
    lines.append(f"\n{effort_count} efforts, {doc_count} documents.\n")

    INDEX.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {INDEX} — {effort_count} efforts, {doc_count} documents")


if __name__ == "__main__":
    main()
